theme: jekyll-theme-midnight
<!DOCTYPE html>
<html>
    <head>
        <title>Concerning Hobbits</title>
    </head>
    <body>
        <h1>Welcome!</h1>
        <p>Just a simple website for the purpose of owning a domain, don't expect to find anything here.</p>
    </body>
</html>
